### ISSUE TITLE
I tried to install wordpress and pressbooks via wp-cli but did not succeed. 

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/docs#3]
Maybe you see what I was doing wrongly. Also I had to manually edit -url="localhost" to -url="127.0.0.1" and rerun the script as it did not use that parameter during creating wp-config.php and with localhost it did not work at all which seems to be a common problem (?).

Am I right in thinking that wordpress does not need to be there as it is also downloaded?

**Script:**
export PATH=$PATH:/Applications/MAMP/Library/bin/
wp core download
wp core config --dbname="wordpress" --dbuser="wordpress" --dbpass="wordpress" --extra-php <<PHP
/* Pressbooks */
define( 'WP_DEFAULT_THEME', 'pressbooks-book' );
define( 'PB_PRINCE_COMMAND', '/usr/local/bin/prince' );
define( 'PB_EPUBCHECK_COMMAND', '/usr/bin/java -jar /opt/epubcheck/epubcheck.jar' );
define( 'PB_XMLLINT_COMMAND', '/usr/bin/xmllint' );
define( 'PB_SAXON_COMMAND', '/usr/bin/java -jar /opt/saxon-he/saxon9he.jar' );
PHP
wp core install --url="127.0.0.1" --title="Pressbooks" --admin_user="wordpress" --admin_password="wordpress" --admin_email="t.dumm@delivros.ch"
wp core multisite-convert --title="Pressbooks"
wp plugin delete hello
wp plugin update-all
wp plugin install https://github.com/pressbooks/pressbooks/releases/download/4.0.0/pressbooks-4.0.0.zip --activate-network
wp theme install https://github.com/pressbooks/pressbooks-book/releases/download/1.9.0/pressbooks-book-1.9.0.zip
wp theme install https://github.com/pressbooks/pressbooks-publisher/archive/master.zip
wp theme install https://github.com/pressbooks/pressbooks-clarke/archive/master.zip
wp theme list
wp theme enable pressbooks-book --network
wp theme enable pressbooks-clarke --network

**Error log:**
Thomas-Dumms-iMac:wordpress thomas$ ./cli_install_pressbooks.sh 
Error: WordPress files seem to already be present here.
Error: The 'wp-config.php' file already exists.
WordPress is already installed.
The network already exists.
Deleted 'hello' plugin.
Success: Deleted 1 of 1 plugins.
Success: Plugin already updated.
Downloading install package from https://github.com/pressbooks/pressbooks/releases/download/4.0.0/pressbooks-4.0.0.zip...
Unpacking the package...
Installing the plugin...
Warning: The package could not be installed. "The plugin contains no files."
Plugin install failed.
Error: No plugins installed.
Downloading install package from https://github.com/pressbooks/pressbooks-book/releases/download/1.9.0/pressbooks-book-1.9.0.zip...
Unpacking the package...
Installing the theme...
Warning: The package could not be installed. "The theme contains no files."
Theme install failed.
Error: No themes installed.
Downloading install package from https://github.com/pressbooks/pressbooks-publisher/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-publisher-master' to 'pressbooks-publisher'.
Theme installed successfully.
Success: Installed 1 of 1 themes.
Downloading install package from https://github.com/pressbooks/pressbooks-clarke/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-clarke-master' to 'pressbooks-clarke'.
This theme requires a parent theme. Checking if it is installed...
The parent theme could not be found. You will need to install the parent theme, pressbooks-book, before you can use this child theme.
Theme installed successfully.
Success: Installed 1 of 1 themes.
+----------------------+----------+--------+---------+
| name                 | status   | update | version |
+----------------------+----------+--------+---------+
| pressbooks-publisher | active   | none   | 3.1.0   |
| twentyfifteen        | inactive | none   | 1.8     |
| twentyseventeen      | inactive | none   | 1.3     |
| twentysixteen        | inactive | none   | 1.3     |
+----------------------+----------+--------+---------+
Error: This is not a multisite install.
Error: This is not a multisite install.

**Comment by greatislander** [comment]
First thing: https://github.com/pressbooks/pressbooks/#important

That script won't work when WordPress is already installed.

It looks like wp-cli can't download release assets from GitHub so I'll have to update these instructions. You could just download them and install them manually.

**Comment by thomasdumm** [comment]
no wordpress was installed when I started the script the first time. The script failed, as it did not work with localhost in wp-config. I then edited localhost in the wp-config to 127.0.0.1 and ran the script again leading to the above log.

**Comment by greatislander** [comment]
Please try the wp-cli commands for Pressbooks and Pressbooks Book again. The release assets had a problem that was preventing them from extracting properly.

```
wp plugin install https://github.com/pressbooks/pressbooks/releases/download/4.0.0/pressbooks-4.0.0.zip
wp theme install https://github.com/pressbooks/pressbooks-book/releases/download/1.9.1/pressbooks-book-1.9.1.zip
```

You may need to reset your database, delete the core and config files and start from scratch knowing the issue with `127.0.0.1` vs `localhost` as just running the whole script on a partially configured site will cause errors. Note that I've updated the script to use one command (`wp core multisite-install`) instead of the previous two (`wp core install`, `wp core multisite-convert`).
