### ISSUE TITLE
The wp-cli based installation from scratch with no wordpress pre-installed looks better now. 3 issues remain:

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/docs#4]
The wp-cli based installation from scratch with no wordpress pre-installed looks better now.
2 issues remain:
- The wp-cli based installation needs the hm-autoloader.php, which is not available at the time as the whole wordpress folder only gets created during the wp-cli based installation. I get the error:
 Fatal error: Call to undefined function HM\Autoloader\register_class_path() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/pressbooks/pressbooks.php on line 77
- For some reason with Mamp Server wp-cli based installation only works with  define( 'DB_HOST', '127.0.0.1' ) in the wp-config file. I always get a wp-config file with define( 'DB_HOST', 'localhost' ). If I manually edit the created wp-config file and rund the script a second time it goes through. But I know I should not run the script twice. But how do I solve the 127.0.0.1 issue?

See installation log of the second install run (I know I should not do that...). The first two error messages are due to the second run. But if I do not edit the wp-config.php file it does not workat all.

**Comment by thomasdumm** [comment]
Error: WordPress files seem to already be present here.
Error: The 'wp-config.php' file already exists.
Single site database tables already present.
The network already exists.
Deleted 'hello' plugin.
Success: Deleted 1 of 1 plugins.
Downloading update from https://downloads.wordpress.org/plugin/akismet.3.3.3.zip...
Using cached file '/Users/thomas/.wp-cli/cache/plugin/akismet-3.3.3.zip'...
Unpacking the update...
Installing the latest version...
Removing the old version of the plugin...
Plugin updated successfully.
+---------+-------------+-------------+---------+
| name    | old_version | new_version | status  |
+---------+-------------+-------------+---------+
| akismet | 3.3.2       | 3.3.3       | Updated |
+---------+-------------+-------------+---------+
Success: Updated 1 of 1 plugins.
Downloading install package from https://github.com/pressbooks/pressbooks/releases/download/4.0.0/pressbooks-4.0.0.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Network-activating 'pressbooks'...
Warning: Could not activate the 'pressbooks' plugin.
Success: Installed 1 of 1 plugins.
Downloading install package from https://github.com/pressbooks/pressbooks-book/releases/download/1.9.1/pressbooks-book-1.9.1.zip...
Unpacking the package...
Installing the theme...
Theme installed successfully.
Success: Installed 1 of 1 themes.
Downloading install package from https://github.com/pressbooks/pressbooks-publisher/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-publisher-master' to 'pressbooks-publisher'.
Theme installed successfully.
Success: Installed 1 of 1 themes.
Downloading install package from https://github.com/pressbooks/pressbooks-austenclassic/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-austenclassic-master' to 'pressbooks-austenclassic'.
This theme requires a parent theme. Checking if it is installed...
The parent theme, Luther 1.9.1, is currently installed.
Theme installed successfully.
Success: Installed 1 of 1 themes.
Downloading install package from https://github.com/pressbooks/pressbooks-clarke/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-clarke-master' to 'pressbooks-clarke'.
This theme requires a parent theme. Checking if it is installed...
The parent theme, Luther 1.9.1, is currently installed.
Theme installed successfully.
Success: Installed 1 of 1 themes.
Downloading install package from https://github.com/pressbooks/pressbooks-donham/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-donham-master' to 'pressbooks-donham'.
This theme requires a parent theme. Checking if it is installed...
The parent theme, Luther 1.9.1, is currently installed.
Theme installed successfully.
Success: Installed 1 of 1 themes.
Downloading install package from https://github.com/pressbooks/pressbooks-fitzgerald/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-fitzgerald-master' to 'pressbooks-fitzgerald'.
This theme requires a parent theme. Checking if it is installed...
The parent theme, Luther 1.9.1, is currently installed.
Theme installed successfully.
Success: Installed 1 of 1 themes.
Downloading install package from https://github.com/pressbooks/pressbooks-custom-css/archive/master.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'pressbooks-custom-css-master' to 'pressbooks-custom-css'.
This theme requires a parent theme. Checking if it is installed...
The parent theme, Luther 1.9.1, is currently installed.
Theme installed successfully.
Success: Installed 1 of 1 themes.
Error: This is not a multisite install.
Error: This is not a multisite install.
Error: This is not a multisite install.
Error: This is not a multisite install.
Error: This is not a multisite install.
Error: This is not a multisite install.

**Comment by greatislander** [comment]
So after installing Pressbooks you'd need to run `mkdir wp-content/mu-plugins && cp wp-content/plugins/pressbooks/hm-autoloader.php wp-content/mu-plugins`. The other issue is with MAMP, not our install instructions. I suggest using [Laravel Valet](https://code.tutsplus.com/tutorials/using-laravel-valet-for-wordpress-development--cms-26519) instead.

**Comment by greatislander** [comment]
(In future, please re-open an existing issue if it's not solved for you rather than creating a new issue about the same topic.)

**Comment by thomasdumm** [comment]
As you can see from the logfile the autoloader is already needed during installation of pressbooks. The missing autoloader results in the error:

Fatal error: Call to undefined function HM\Autoloader\register_class_path() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/pressbooks/pressbooks.php on line 77

I presume that this error message schould not be there.

**Comment by greatislander** [comment]
It's needed during the activation, not the installation. So you can split this into two steps:

```diff
-- wp plugin install https://github.com/pressbooks/pressbooks/releases/download/4.0.0/pressbooks-4.0.0.zip --activate-network
++ wp plugin install https://github.com/pressbooks/pressbooks/releases/download/4.0.0/pressbooks-4.0.0.zip
mkdir wp-content/mu-plugins && cp wp-content/plugins/pressbooks/hm-autoloader.php wp-content/mu-plugins
++ wp plugin activate pressbooks --network
```
