### ISSUE TITLE
Linux dependency- Microsoft Fonts

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/docs#41]
Add a bullet in Part 3: Pressbooks Dependencies reminding Linux users to install the Microsoft Core Fonts.

Steel helped me troubleshoot a problem that took a few hours in this thread.
https://pressbooks.community/t/best-way-to-track-down-unicode/1606/12

https://www.princexml.com/doc/fonts/

**Comment by SteelWagstaff** [comment]
Done! https://github.com/pressbooks/docs/commit/9faaae5e61f0a989c996d9304ca53ebc1739ac09. Still figuring out how to sync with the docs site, but should be up soon. Thanks @beckej13820

**Comment by SteelWagstaff** [comment]
Update to installation page on docs site has been published.
