### ISSUE TITLE
Feedback on the https://docs.pressbooks.org/installation/

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/docs#5]
After step 3 the autoloader file has to be copied to the mu-plugins folder https://docs.pressbooks.org/upgrading/#autoloader . That step is mentioned in the update doc but not in the fresh install doc.

After copying the pressbooks-publisher folder to the themes folder the folder has to be named to pressbooks-publisher (without version number)

WRONG
define( 'PB_EPUBCHECK_COMMAND', '/usr/bin/epubcheck' );

CORRECT
define( 'PB_EPUBCHECK_COMMAND', '/usr/bin/java -jar /usr/bin/epubcheck/epubcheck.jar' );

**Comment by greatislander** [comment]
Hi @thomasdumm, can I ask that in future you try to open a pull request which makes the specific changes you are proposing? Thanks. See: https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution

I'll make the changes as indicated in your first two points. However, the docs do indicate that the value for `PB_EPUBCHECK_COMMAND` depends on your system:

> Once installed, define the following wp-config.php variables. The defaults are:

 ```
define( 'PB_PRINCE_COMMAND', '/usr/bin/prince' );
define( 'PB_KINDLEGEN_COMMAND', '/opt/kindlegen/kindlegen' );
define( 'PB_EPUBCHECK_COMMAND', '/usr/bin/epubcheck' );
define( 'PB_XMLLINT_COMMAND', '/usr/bin/xmllint' );
define( 'PB_SAXON_COMMAND', '/usr/bin/java -jar /opt/saxon-he/saxon-he.jar' );```

I understand that in your case the default is not `/usr/bin/epubcheck` but that's the default that we have established. We can't possibly have a default value that works on everyone's system, so we've chosen a default that makes sense for us (the path to Epubcheck when installed [via apt](https://launchpad.net/ubuntu/+source/epubcheck) on an Ubuntu/Debian system). You will always have to adjust these values to the specifics of your system.

**Comment by thomasdumm** [comment]
Ok. I will try with the pull request. never did that. I am only a semi-poweruser.
About the PB_EPUBCHECK_COMMAND value. The path to the jar file is system dependent. But you probably always have to have this in front of the path: /usr/bin/java -jar (as in the PB_SAXON_COMMAND)?

**Comment by greatislander** [comment]
Nope. The apt package that I linked to actually installs a binary of Epubcheck rather than a jarfile.

**Comment by thomasdumm** [comment]
OK
