### ISSUE TITLE
update PB dependency instructions on installation.md

### ISSUE THREAD

**Issue by JackDougherty** [pressbooks/docs#6]
On this documentation page
https://docs.pressbooks.org/installation/#part-3-pressbooks-dependencies

Steps we had to figure out that were not included:
1) Install Java on your server
sudo apt install default-jre

2) the current documentation points to:
define( 'PB_EPUBCHECK_COMMAND', '/usr/bin/epubcheck' );

But we could only make it work by pointing to:
define( 'PB_EPUBCHECK_COMMAND', '/usr/bin/java -jar /usr/bin/epubcheck/epubcheck.jar' );

which differs from Dac's example further below in your documentation:
define( 'PB_EPUBCHECK_COMMAND', '/usr/bin/java -jar /home/dac514/bin/epubcheck-4.0/epubcheck-4.0.jar' );

Perhaps the PB team has better instructions, but the current version did not work for our recent upgrade to PB 4.x, and we've been using PB for several years.

**Comment by greatislander** [comment]
> but the current version did not work for our recent upgrade to PB 4.x

You mean the current version of the instructions?

1. Yes, Java is a prerequisite; we assume that in following the instructions for Epubcheck and Saxon-HE users will be instructed that they need to install Java but you're right that this could be included in the installation instructions.
2. If you are using a Debian or Ubuntu server (which we do) you can install the Epubcheck apt package which puts a binary at `/usr/bin/epubcheck`. Other systems may need to do this differently. @connerbw's example is pretty old and we could probably update that too. If your system does support apt packages we suggest using the apt package for Epubcheck.

**Comment by JackDougherty** [comment]
Thanks for replying. Yes, I was referring to the current instructions. I will share your suggestions with my sys admin.
